[project]
name = "experiment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gpiozero>=2.0.1",
    "httpx>=0.28.1",
    "pi-rc522>=2.3.0",
    "pigpio>=1.78",
    "rpi-lgpio>=0.6",
    "structlog>=25.5.0",
]
